### ISSUE TITLE
Use TH Exp as AST?

### ISSUE THREAD

**Issue by Zemyla** [mvdan/hint#19]
I'm wondering if it would be useful to have an interpret command that takes, instead of a String, an Exp  from Language.Haskell.TH.Syntax. GHC already has functions to turn those into executable code, and it would increase composability - being able to produce part of an expression in another function as an object instead of a string.

**Comment by mvdan** [comment]
I don't see why not - patches welcome.

**Comment by mvdan** [comment]
This has been up for grabs for close to two years, but it seems like there isn't interest in getting it implemented. Since I won't implement it myself, I'm closing the issue for now. Feel free to reopen if you'd still like to work on this.
