### ISSUE TITLE
Execute IO action in Interpreter

### ISSUE THREAD

**Issue by avonb** [mvdan/hint#21]
Is there a way to execute an IO expression with eval or interpret? I'm sure there is, but I'm too inexperienced to get it running. Could you provide and example for this? 

Thank you.  

Edit:
Something like this

```
run :: IO String
run = do 
   r <- runInterpreter $ do            
            set[searchPath := ["path"]]
            loadModules ["module"]
            setTopLevelModules ["module"]
            setImportsQ [("Prelude", Nothing), ("Data.Map", Just "M")]            
            eval "putStrLn \"HelloWorld\""
   return r
```

**Comment by mvdan** [comment]
Just why would you want to do this, exactly? If you want to print a variable in the interpreter, you shoud print its interpretation, not evaluate its printing.

**Comment by gelisam** [comment]
>     eval "putStrLn \"HelloWorld\""

The first problem is that `eval` can only return strings. Use `interpret`, which can return a value of any type:

    interpret "putStrLn \"HelloWorld\"" (as :: IO ())

This successfully evaluates the expression and returns it, but it does not *execute* it. That is:

1. `putStrLn "HelloWorld"` has type `IO ()`
1. `interpret "putStrLn \"HelloWorld\"" (as :: IO ())` has type `Interpreter (IO ())`
1. `r <- runInterpreter (interpret "putStrLn \"HelloWorld\"" (as :: IO ()))` has type `IO (Either InterpreterError (IO ()))`
1. `r` has type `Either InterpreterError (IO ())`

So you still need to extract the `IO ()` operation and execute it:

    -- |
    -- >>> main
    -- executing the action:
    -- HelloWorld
    main :: IO ()
    main = do
        r <- runInterpreter $ do
          setImports ["Prelude"]
          interpret "putStrLn \"HelloWorld\"" (as :: IO ())
        case r of
          Left err -> do
            putStrLn "some error occurred:"
            print err
          Right action -> do
            putStrLn "executing the action:"
            action
