### ISSUE TITLE
Imported package modules don't have their imports

### ISSUE THREAD

**Issue by MasterMastic** [mvdan/hint#22]
I just tried to import a module from a (separate) package of mine and I'm getting errors that there are symbols that the module uses that are not in scope.

I could minimize it to an extent by importing the modules that are missing in the interpreter but it's not very feasible, and I actually tried but I got name clashes when the module I'm trying to import only imports some symbols from a module, and so on. It's also very tedious with a lot of imports.

I'm not sure if I hit a limitation or a bug or maybe I'm not doing something correctly.

**Comment by gelisam** [comment]
Sounds unlikely, do you have a minimal example?

**Comment by mvdan** [comment]
As @gelisam said, a working minimal example would be very useful here.

**Comment by MasterMastic** [comment]
I'll try to come up with something right now.
I tried once and couldn't reproduce, but it happens for sure in an actual project, so I'll try to investigate what's happening.

**Comment by mvdan** [comment]
Sounds good. This issue is a little vague and not easily reproducible, so unless you come up with an example I'll have to close it at some point since no progress would ever be made.

**Comment by MasterMastic** [comment]
Two updates:
A) I found that it's not even about trying to import a module, it's about the type I `infer`/`as`. If it comes from another module, sometimes it's problematic, and sometimes it's not, e.g. below it's problematic with `text`, in my project it's problematic both with `text` and my modules in the separate package, and in my mentioned first attempt, it was completely fine with definitions that are in a separate package.
B) I found one case with using `text`:

```
import Data.Text (Text)
import Language.Haskell.Interpreter

main :: IO ()
main = (=<<) print . runInterpreter $ do
  setImports ["Prelude"]
  interpret "Nothing" (as :: Maybe Text)
```
Fails:
```
ghci> main
Left (WontCompile [GhcError {errMsg = "<interactive>:3:42: error:\n    Not in scope: type constructor or class `Text'"}])
```

As mentioned, I'm getting error with `text` in my actual project too, although I'm getting the same thing with definitions in my other package.

**Comment by mvdan** [comment]
I confirm the same error with `runghc`, `hint-0.6.0` and `text-1.2.2.1`.

Do you have an example of when this does work?

**Comment by MasterMastic** [comment]
Package `p1` has just module `P1.A`:

`
module P1.A where data A = A deriving Show
`

Package `p2` depends on `p1` and has module `P2`:

```
module P2 where
import Language.Haskell.Interpreter
import P1.A

main :: IO ()
main = (=<<) print . runInterpreter $ do
  setImports ["Prelude", "P1.A"]
  interpret "A" (as :: A)
```

Session:
```
ghci> main
Right A
```

**Comment by mvdan** [comment]
Do you have any working example with a package that you installed through cabal/stack? Maybe this has something to do with how you installed the separate package.

**Comment by MasterMastic** [comment]
I don't. `p1` was installed in `p2` through stack via the `packages` field in `stack.yaml` and it worked. In my actual project this is the same way I included my separate project and it failed.

Is there anything I should do when installing packages normally (e.g. like `text`) so that they'll work with the interpreter?

**Comment by mvdan** [comment]
> Is there anything I should do when installing packages normally (e.g. like text) so that they'll work with the interpreter?

Not that I know.

On my own usage of `hint`, I've found that depending on what the code does, the binary will crash if compiled and executed separately, whereas it won't if I just `runghc` it. I haven't had time to binary-search exactly what part of the code is causing this, as a `hint` "Hello World" does work in both cases.

I suspect a similar approach would work here. `text` is a complex package, and your example `p2` is a simple one. I assume `hint` breaks at some point between these two for a specific reason, which could probably be found if you start removing parts from `text` until it starts working.

Also, playing with it now, I think I found it. This works:

```
import Data.Text (Text)
import Language.Haskell.Interpreter

main :: IO ()
main = (=<<) print . runInterpreter $ do
  setImports ["Prelude", "Data.Text"]
  interpret "Nothing" (as :: Maybe Text)
```

**Comment by MasterMastic** [comment]
I see, so would you consider this a bug? and would you advise me to use a DSL instead of trying to interpret Haskell, at least for the time being?

And by the way, as I noted in my OP, importing in the interpreter does help but it's not so feasible, perhaps it could be a bit more if there was a way to choose what to import from a module within the interpreter (e.g. an equivalent to `import MyModule (x,y,z)`).

**Comment by mvdan** [comment]
I don't think this is a bug - I don't see how the interpreter would have access to the imports if it's not told about them. Also, you did use explicit imports in your "this works" example, so you're not putting the two examples at the same level.

> perhaps it could be a bit more if there was a way to choose what to import from a module within the interpreter (e.g. an equivalent to import MyModule (x,y,z)).

Maybe. Perhaps you could dig into the `hint` source and play with this.

**Comment by MasterMastic** [comment]
I see. Thank you very much!

**Comment by mvdan** [comment]
To clarify - you might be confused in the example having `interpret "Nothing" (as :: Maybe Text)`.

You might think - In the interpreter, I only have `Nothing` which doesn't require `Data.Text`. Why do I need to set it as an import?

What `interpret` does here is generate the code `Nothing :: Maybe Text`, compile it and evaluate it. So it does use `Data.Text`, and it will fail to compile if it doesn't find that.
