### ISSUE TITLE
Serialize Interpreter State and Restart

### ISSUE THREAD

**Issue by SamuelSchlesinger** [mvdan/hint#23]
I would like to serialize interpreter state and store multiple ones at a time for multiple clients, being able to host their interpreters separately but not have them on separate threads. It seems this is not possible at this time, but I'd love to be wrong.

**Comment by mvdan** [comment]
An obvious silly solution is to record all the commands and replay them when needed. That isn't very useful if the computation is expensive or depends on external factors that might change over time, though.

Out of curiosity, are you expecting to have so many concurrent users as to run out of space for threads?

**Comment by mvdan** [comment]
If anyone has time to dig into this, I'll be happy to review code.

**Comment by mvdan** [comment]
Over a year and no interest from anyone to develop the idea or work on it, so I'm going to close this for now. Can be re-opened if that changes in the future.
