### ISSUE TITLE
Catch an interpreter error without restarting interpreter

### ISSUE THREAD

**Issue by yaxu** [mvdan/hint#24]
`runIntepreter` returns `Left InterpreterError` on error. It seems there is no way to deal with interpreter errors while keeping the interpreter running.

This wouldn't be a big deal for me except my code needs to run on a low powered computer (a Raspberry Pi Zero), and it takes a long time to restart the interpreter after each error. I don't see such a delay when I make errors in ghci.

There is the `typechecks` function, but it only returns a boolean value, I need to display the error itself to the user.

Here's what I have at the moment, which works fine apart from being slow to recover from a compile error:
  https://github.com/yaxu/tidal-websocket/blob/master/Sound/Tidal/Hint.hs

**Comment by mvdan** [comment]
If ghci can do it, it's very probable that hint could too since it started a long time ago as a fork of the ghci code.

I picked up maintainership of this package so I'm unfortunately not familiar enough with the internals to know whether this is possible or how to do it. If you or someone else has the time to dig into this, I'll be happy to review code or help in any other way I can.

**Comment by yaxu** [comment]
Thanks @mvdan, I may well not have the Haskell skills for the task, will try to find some time to look at it over the break but if someone else has some time please go ahead !

**Comment by Wizek** [comment]
Yes, this seems like something that could be quite useful indeed. And looking at the source code, it actually might turn out to be quite very simple to implement:

https://hackage.haskell.org/package/hint-0.7.0/docs/src/Hint-Typecheck.html#typeChecks

I'll try to do that now.

**Comment by Wizek** [comment]
I have some good news, @yaxu.

This totally works:

```hs
getType :: MonadInterpreter m => String -> m (Either [GhcError] String)
getType expr = (typeOf expr >>= return . Right)
                              `catchIE`
                              onCompilationError (\a -> return (Left a))
```

based on `typeChecks`.

PR incoming.

**Comment by yaxu** [comment]
Thanks a lot @Wizek !
