### ISSUE TITLE
Question: How to type check arbitrary blocks of code?

### ISSUE THREAD

**Issue by adelbertc** [mvdan/hint#28]
Hey,

Apologies if this is the wrong place to ask, please redirect me if so.

I'm wondering what is the best way to dynamically type check arbitrary blocks of code in hint? It seems like `interpret` is intended for single expressions - if say I wanted to type check:

```haskell
class MyFunctor f where
    mymap :: (a -> b) -> f a -> f b

instance MyFunctor [] where
    mymap = map

doStuff :: MyFunctor f => f a -> f ()
doStuff = map $ const ()
```

is there something built into `hint` to do this? If not, I was thinking of doing something like writing the block to a temporary file, loading the module, and assuming that's OK then call it good?

**Comment by mvdan** [comment]
`interpret` is for expressions, not modules (programs). So yes, as far as I know you must write to a file and load the module.

The way GHC is written - or at least the way we use it - means that modules/programs can only be loaded from `*.hs` files. See https://github.com/mvdan/hint/issues/7.
