### ISSUE TITLE
Possible to deal with the 2x slowdown while using hint?

### ISSUE THREAD

**Issue by saurabhnanda** [mvdan/hint#37]
```
benchmarking without hint
time                 213.0 ms   (208.2 ms .. 224.4 ms)
                     0.999 R²   (0.994 R² .. 1.000 R²)
mean                 208.9 ms   (206.1 ms .. 213.1 ms)
std dev              4.400 ms   (1.590 ms .. 6.449 ms)
variance introduced by outliers: 14% (moderately inflated)

benchmarking with hint
time                 470.8 ms   (187.8 ms .. 591.3 ms)
                     0.959 R²   (0.878 R² .. 1.000 R²)
mean                 488.7 ms   (447.3 ms .. 512.5 ms)
std dev              36.99 ms   (0.0 s .. 41.13 ms)
variance introduced by outliers: 21% (moderately inflated)
```

Benchmark available at https://github.com/vacationlabs/hint-test

**Comment by mvdan** [comment]
Is that time including Hint loading the modules, or just running them?

In any case, there has to be some amount of overhead. I assume you weren't expecting Hint to be as fast as compiled code.

**Comment by saurabhnanda** [comment]
> Is that time including Hint loading the modules, or just running them?

Just running them. Could you please look at the code at https://github.com/vacationlabs/hint-test/blob/abcc43dd0199356494ef9881be2fcea85d216584/app/Main.hs#L15-L48 to confirm that module loading is not being included in the benchmark times?

> In any case, there has to be some amount of overhead. I assume you weren't expecting Hint to be as fast as compiled code.

Actually, I **was expecting** that module loading/compilation may take some time, but after that it would run at the same speed. Why is this slower than normally compiled code?

**Comment by gelisam** [comment]
hint does not compile the code, it interprets it, just like ghci. You can, however, compile a module and load it from hint/ghci. See [my experimentations](https://github.com/gelisam/hawk/issues/126) on the subject.

**Comment by gelisam** [comment]
Summary: you have to install the package to a package database, calling ghc on your source file is not sufficient for hint/ghci to use the compiled version.

**Comment by saurabhnanda** [comment]
@gelisam that's quite a thread you have there! Did you figure out a way to trigger actual compilation instead of interpretation? Is it somehow related to https://downloads.haskell.org/~ghc/7.6.3/docs/html/users_guide/ghci-obj.html ?

**Comment by saurabhnanda** [comment]
> Summary: you have to install the package to a package database, calling ghc on your source file is not sufficient for hint/ghci to use the compiled version.

So, assuming that I compile the `.hs` file to a `.o` and `.hi` file, what magic incantation do I need to give `hint` so that it uses the `.o/.hi` files?

**Comment by gelisam** [comment]
I did not know about `-fobject-code`, thanks!

**Comment by saurabhnanda** [comment]
> I did not know about -fobject-code, thanks!

Is it possible for `hint` to use `-fobject-code` somehow?

**Comment by gelisam** [comment]
Maybe with [`unsafeRunInterpreterWithArgs`](http://hackage.haskell.org/package/hint-0.7.0/docs/Language-Haskell-Interpreter-Unsafe.html#v:unsafeRunInterpreterWithArgs)?

**Comment by saurabhnanda** [comment]
> Maybe with unsafeRunInterpreterWithArgs?

Erroring out with:

```
Error while running the interpreter: GhcException "Cannot add module M512196972046601278612963 to context: not interpreted"
```

**Comment by gelisam** [comment]
> what magic incantation do I need to give hint so that it uses the `.o/.hi` files?

To [quote myself](https://github.com/gelisam/hawk/issues/126#issuecomment-74609425) from that thread: you need a `.dylib` file, not a `.o`!

I believe the trick is to install your code to a package database using `cabal install`, to point hint to it using something like `unsafeRunInterpreterWithArgs ["-package-db ./.cabal-sandox/x86_64-osx-ghc-8.0.2-packages.conf.d"]`, and then to import your compiled code using `setImports` or `setImportsQ`. The code you load using `loadModules` will always be interpreted (except perhaps using `-fobject-code`, which I haven't tried yet), so it must be a small shim which calls the compiled code from the package you've just installed.

At least, that's what I can conclude from reading my own thread; it's been a while, I don't remember all the details...

**Comment by saurabhnanda** [comment]
> I believe the trick is to install your code to a package database using cabal install

Did you create a separate local package for your plugin/HS file, or did you compile a standalone file using `-dynamic -fPIC -shared` and then copy it to the correct place manually?

**Comment by gelisam** [comment]
I used `cabal install`, but obviously cabal is using ghc and ghc-pkg under the hood, so you could run cabal verbosely to see what it does, figure out what is the minimal set of commands necessary for what you need, and only run those. I don't know if the particular set of flags you gave would be sufficient, but at the minimum you would also need to update the package database to register your new package. Hmm, unless you were overwriting a file from an existing package...

**Comment by mvdan** [comment]
It seems to me like there's nothing to fix or add in `hint`, so I'm closing this issue for now. If I'm wrong, or if this situation changes in the future, feel free to reopen this issue or create a new one. Thanks!
