### ISSUE TITLE
module loading: search path for compiled modules?

### ISSUE THREAD

**Issue by jwaldmann** [mvdan/hint#44]
For `setImports`, it is not clear to me how these modules are found at run-time. 

From experiments, I conclude that this is using the installed ghc's global package directory, so I need to install the modules I want to use with `cabal install --global` (which is deprecated).

Is there a way to influence this? E.g., so that it also picks up "$HOME/.ghc" - as `ghci` would do?

The documentation mentions `searchPath` but it says this is the "path for source files". My use case is about loading compiled modules.

(this is with hint-0.7.0 from stackage nightly-2017-11-10 and ghc-8.2.1)

**Comment by gelisam** [comment]
I use [`unsafeRunInterpreterWithArgs`](https://hackage.haskell.org/package/hint-0.7.0/docs/Language-Haskell-Interpreter-Unsafe.html#v:unsafeRunInterpreterWithArgs) to send the same [`-package-db`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/packages.html#ghc-flag--package-db) argument I'd give to `ghc` from the command line.

**Comment by mvdan** [comment]
Assuming this is enough of a solution, given that there wasn't a reply. If it's not, or if you have a suggestion or a patch, feel free to reopen.

**Comment by jwaldmann** [comment]
Meanwhile I found that `$HOME/.ghc/x86_64-linux-X.Y.Z/package.conf.d` *is* actually read, but in my use case, `$HOME` was wrong/unset, so that step failed (silently).
