### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by mvdan** [mvdan/hint#47]
I picked up hint in early 2016 because I needed to use it for a project at university, and I needed it to support the latest GHC version at the time. While at it, other work was done like adding CI and cleaning up the codebase.

That project finished long ago, so I no longer have a reason to actively maintain hint. I haven't abandoned it, but as one can see by the number of issues and pull requests, it requires someone with more time and incentive to do work.

If anyone would be interested in maintaining the project, I'd gladly hand it over and we can move this GitHub repo somewhere else. Ideally an organization so that the repo lives at `github.com/some-org/hint`, so that we don't have a bus factor like we do now.

/cc @gelisam @int-e @jcpetruzza @meditans and others

**Comment by gelisam** [comment]
I can't say I have enough bandwidth to _actively_ maintain hint (open issues are also piling up in my other open source projects), but if you need to take some time off of the project, I can at least respond to new issues as they come up. Unless they come with a PR, they're likely to remain open though.

**Comment by mvdan** [comment]
I don't think one maintainer with lots of time would be necessary - perhaps three or four with a little time here and there would be enough. I simply don't want to be the bottleneck nor own the repository in that scenario.

And yeah, I'm not too worried about the enhancement issues that have no pull requests. A bit more worried about the bugs, questions, and open PRs, though.

**Comment by Wizek** [comment]
@mvdan By the way, you may find this article interesting:

- http://felixge.de/2013/03/11/the-pull-request-hack.html
- Also, there is some discussion around it here: https://www.reddit.com/r/programming/comments/1a7gns/whenever_somebody_sends_you_a_pull_request_give/

**Comment by mvdan** [comment]
I remember reading that - certainly interesting, and I'm definitely in favor of giving write acces to anyone who wants it and has contributed. @gelisam already has it.

But I don't think handing it out to someone before they have contributed is a good plan - could backfire in fun ways. Any maintainer is better than no maintainer, but we're not there yet :)

**Comment by mvdan** [comment]
Now that @gelisam is helping me a bit more, I think we're fine for the time being. And it's not like anyone has stepped up to take a more active role. Closing for now.

**Comment by gelisam** [comment]
Well, looks like I'm the de facto maintainer now. I didn't want to take on yet another project, because I have so many on my plane now that each of them gets very little of my time, but it looks like I'm the one who cares the most about keeping hint alive :)
