### ISSUE TITLE
Module files should not be requried to have the .hs extension

### ISSUE THREAD

**Issue by TomMD** [mvdan/hint#7]
This might require a patch upstream to GHC, I admit.  I'm looking for thoughts so I can take the next steps.

When loading a module of some arbitrary extension the GhcException message is:

```
target ‘Small.mpc’ is not a module name or a source file
```

Which is rather unfortunate.  I have a habit of using hint to get free lexing/parsing/type checking to build a stand-alone compiler for DSLs (interpret the source to generate an AST, compile the AST using optimized machine code from there) and I would like those DSLs to be allowed to have non-haskell extensions.

**Comment by mvdan** [comment]
This would be nice to have. I work around a similar problem - apparently GHC cannot take a module from a string or buffer, only a file path. So I create temporary files instead.

Both of those features would be nice to have, but it all depends on whether vanilla GHC allows for any of this. If it doesn't, there isn't much we can do on our side.

**Comment by mvdan** [comment]
I still believe that this is a limitation coming from GHC. And it sure seems so - search for `isHaskellSrcFilename` in the GHC sources. I'm going to close this for now.

If anyone comes up with a way to work around or fix this limitation, please open a new issue.
